import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import NextAuthProvider from './providers/NextAuthProvider'
import ReactQueryClientProvider from './providers/ReactQueryClientProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryClientProvider>
          <NextAuthProvider>
            {children}
          </NextAuthProvider>
        </ReactQueryClientProvider>
      </body>
    </html>
  )
}
